---

- name: restart kube-scheduler
  systemd:
    name: kube-scheduler
    state: restarted
    enabled: yes
  become: yes

- name: restart kube-apiserver
  systemd:
    name: kube-apiserver
    state: restarted
    enabled: yes
  become: yes

- name: restart kube-controller-manager
  systemd:
    name: kube-controller-manager
    state: restarted
    enabled: yes
  become: yes
